Repository macports/macports-webapp, pull requests merged in 2019-08, with the labels that each got.

#57 docker: Support running as unprivileged user
  Dockerfile
  config/nginx.conf
Labels: enhancement

#82 git_update.py: Do not print to stderr on success
  app/parsing_scripts/git_update.py
Labels: enhancement

#66 Improve the Landing Page
  app/ports/templates/ports/index.html
  app/ports/templates/ports/portdetail.html
Labels: draft

#95 git_update.py: Do not choke on non-port edits
  app/parsing_scripts/git_update.py
  app/ports/tests/test_git_update.py
Labels: bug
